### PR TITLE
A tree builder without a root node is deprecated since Symfony 4.2 an…

### PR DESCRIPTION
**Pull request by lsv**
…d will not be supported anymore in 5.0.

### CODE REVIEW

**Comment by tniemann** [comment]
Is this repo still maintained? Can someone accept the pull request, please!

**Comment by gfreeau** [comment]
@lsv Thanks for taking the time, appreciate it.

**Comment by tniemann** [comment]
@gfreeau can you update the packagist as well? 

Thx
Thomas

**Comment by gfreeau** [comment]
@tniemann @lsv We can't tag a release until the `composer.json` file is updated as well since this change will be incompatible with sf3 for example. Can you please update the symfony/php versions defined in composer.json.

Then we can tag a new 3.0 release for >= sf4 only.

**Pull request merged**
