### PR TITLE
Replace UserChecker if using Symfony 2.8+

### LINKED ISSUE #12: Symfony 2.8 upgrade breaks this bundle
Error:

```bash
[Symfony\Component\Debug\Exception\ContextErrorException]
  Catchable Fatal Error: Argument 2 passed to Symfony\Component\Security\Core\Authentication\Provider\DaoAuthenticationProvider::__construct() must be an instance of Symfony\Component\Security\Core\User\UserCheckerInterface, string given, called in /run/shm/user/cache/dev/appDevDebugProjectContainer.php on line 10854 and defined
```

### PR DESCRIPTION
**Pull request by guilhermeblanco**
Fixes #12 

Once merged, please create a new release. =)

### CODE REVIEW

**Comment by hacfi** [comment]
:+1:

**Comment by gfreeau** [comment]
Thanks

**Comment by guilhermeblanco** [comment]
:+1: Be ready for another one soon for Symfony 3.0 compatibility (just saw your composer.json that prevent installing it). Should be `"symfony/symfony": "~2.3|~3.0"`. Didn't check consequences with this change yet.

**Comment by guilhermeblanco** [comment]
Please update packagist with the new tag. =)

**Comment by gfreeau** [comment]
@guilhermeblanco should be up there now.

**Comment by guilhermeblanco** [comment]
@gfreeau already deployed my app... working like a charm! =)

**Pull request merged**
