### PR TITLE
[FEATURE] Accept json

### PR DESCRIPTION
**Pull request by nchagrass**

### CODE REVIEW

**Comment by gfreeau** [comment]
Thank you, I will review it.

**Comment by nchagrass** [comment]
It's actually a duplicate of #11

**Comment by gfreeau** [comment]
It is, I'd like to do another stable release even though symfony 3.3+ may have a similar feature as lots of people are not using that version.

So we need to decide which pull request is going to be merged here.

**Comment by gfreeau** [comment]
I think we should just merge the other PR. This will include this functionality as well.

**Comment by nchagrass** [comment]
Up to you, let me know if I can help in any way

**Comment by nchagrass** [comment]
Not required any more as it is now included in Symfony 3.3.*

**Pull request closed without merging**
